.PHONY: clean All

All:
	@echo "----------Building project:[ sectionChallenge - Debug ]----------"
	@cd "sectionChallenge" && "$(MAKE)" -f  "sectionChallenge.mk"
clean:
	@echo "----------Cleaning project:[ sectionChallenge - Debug ]----------"
	@cd "sectionChallenge" && "$(MAKE)" -f  "sectionChallenge.mk" clean
